-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('DELIVERED', 'IN_TRANSIT', 'PICKUP_SCHEDULED', 'ORDER_CONFIRMED', 'ORDER_PLACED');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "status" "OrderStatus" NOT NULL DEFAULT 'ORDER_PLACED';
